# from django.core.management.base import BaseCommand, CommandError
# import subprocess
# 
# class Command(BaseCommand):
    # def handle(self, *args, **options):
        # subprocess.call('/home/rtst15/AutoCheckTimeStamping/run.sh', shell=True)

        # subprocess.call('/home/rtst15/testjango/readcsv/mycommand2.py')
        # print("call end")
        # print("Start (python manage.py shell)")
        # subprocess.call('echo "hi this is bash"', shell=True)
        # subprocess.call('/home/rtst15/AutoCheckTimeStamping/test.sh', shell=True)
        # subprocess.call('python manage.py shell', shell=True)
        # print("End custom command")
